// Demo/fallback data — committed to repo
// Same shape as data.js (generated by refresh.js)
// window.DD_SAMPLE_DATA is set here; script.js checks for DD_DATA first, then DD_SAMPLE_DATA

window.DD_SAMPLE_DATA = {
  meta: {
    org_name: "HKJC (Demo Mode)",
    org_id: "1295457",
    last_updated: "2026-05-12T08:00:00Z",
    is_sample: true
  },

  milestones: {
    core: [
      { id: "dashboard_created", name: "Dashboard Created",                 icon: "📊", points: 150, type: "audit", audit_query: "@action:created @evt.name:Dashboard" },
      { id: "monitor_created",   name: "Alert Configured",                  icon: "🔔", points: 150, type: "audit", audit_query: "@action:created @evt.name:Monitor" },
      { id: "slo_created",       name: "SLO Created",                       icon: "🎯", points: 200, type: "audit", audit_query: "@action:created @evt.name:SLO" },
      { id: "notebook_created",  name: "Notebook Authored",                 icon: "📓", points: 100, type: "audit", audit_query: "@action:created @evt.name:Notebook" },
      { id: "case_created",      name: "Case Created",                      icon: "📋", points: 100, type: "audit", audit_query: "@action:created @evt.name:Case Management" },
      { id: "user_invited",      name: "Team Member Invited",               icon: "👥", points: 100, type: "audit", audit_query: "@action:created @evt.name:Access Management @asset.type:user" },
      { id: "bits_ai_sre",       name: "Trigger Bits AI SRE Investigation", icon: "🤖", points: 200, type: "audit", audit_query: "@action:created @evt.name:Bits AI SRE" }
    ],
    org: [
      { id: "infra_hosts",     name: "Infra Hosts",        icon: "🖥️",  type: "metric", metric: "datadog.estimated_usage.hosts" },
      { id: "containers",      name: "Containers",         icon: "📦",  type: "metric", metric: "datadog.estimated_usage.containers" },
      { id: "apm_active",      name: "APM",                icon: "🔭",  type: "metric", metric: "datadog.estimated_usage.apm_hosts" },
      { id: "ingested_spans",  name: "APM Ingested Spans", icon: "🕸️",  type: "metric", metric: "datadog.estimated_usage.apm.ingested_spans" },
      { id: "logs_active",     name: "Log Management",     icon: "📋",  type: "metric", metric: "datadog.estimated_usage.logs.ingested_events" },
      { id: "rum_active",      name: "RUM",                icon: "🌐",  type: "metric", metric: "datadog.estimated_usage.rum.sessions" },
      { id: "custom_metrics",  name: "Custom Metrics",     icon: "📐",  type: "metric", metric: "datadog.estimated_usage.metrics.custom" },
      { id: "serverless",      name: "Serverless",         icon: "☁️",  type: "metric", metric: "datadog.estimated_usage.fargate_tasks" }
    ],
    day1: [
      { id: "session_1", name: "Observability Overview & Platform Fundamentals", icon: "🎓", points: 100, type: "manual" },
      { id: "session_2", name: "APM Fundamentals & Application Troubleshooting", icon: "🔭", points: 100, type: "manual" },
      { id: "session_3", name: "RUM & End-to-End User Journey Visibility",       icon: "🌐", points: 100, type: "manual" }
    ],
    day2: [
      { id: "session_4", name: "Bits AI for Incident Investigation & Postmortem", icon: "🤖", points: 100, type: "manual" },
      { id: "session_5", name: "Monitor & Alerting Best Practices",               icon: "🔔", points: 100, type: "manual" },
      { id: "session_6", name: "Dashboarding for Operational Visibility",         icon: "📊", points: 100, type: "manual" }
    ],
    self_learning: [
      { id: "learning_path", name: "Persona Based Learning Path", icon: "🎯", points: 150, type: "manual" }
    ],
    special: [
      { id: "dbm_active",       name: "DBM Enabled",        icon: "🗄️",  points: 300, type: "metric", metric: "datadog.estimated_usage.dbm.hosts" },
      { id: "profiling_active", name: "Continuous Profiler", icon: "🔍",  points: 300, type: "metric", metric: "datadog.estimated_usage.profiling.hosts" },
      { id: "network_active",   name: "Network Monitoring",  icon: "🕸️",  points: 300, type: "metric", metric: "datadog.estimated_usage.network.hosts" }
    ],
    advance: [
      { id: "cert_fundamentals", name: "Datadog Fundamentals",   icon: "📜", points: 500, type: "manual" },
      { id: "cert_apm",          name: "Datadog APM Cert",       icon: "🏆", points: 500, type: "manual" },
      { id: "cert_logs",         name: "Datadog Log Management", icon: "🪵", points: 500, type: "manual" }
    ]
  },

  certification_tiers: [
    // Bronze: complete Day 1 opening session + first dashboard + first monitor
    { id: "bronze",   name: "Bronze",   icon: "🥉", color: "#cd7f32", gc_bonus: 200,
      required: ["session_1", "dashboard_created", "monitor_created"] },
    // Silver: full Day 1 + SLO
    { id: "silver",   name: "Silver",   icon: "🥈", color: "#c0c0c0", gc_bonus: 300,
      required: ["session_1", "session_2", "session_3", "dashboard_created", "monitor_created", "slo_created"] },
    // Gold: full Day 2 + notebook + Bits AI SRE
    { id: "gold",     name: "Gold",     icon: "🥇", color: "#f0b429", gc_bonus: 400,
      required: ["session_1", "session_2", "session_3", "dashboard_created", "monitor_created", "slo_created",
                 "session_4", "session_5", "session_6", "notebook_created", "bits_ai_sre"] },
    // Platinum: Gold + learning path + case + invited team member + 2 special achievements
    { id: "platinum", name: "Platinum", icon: "💎", color: "#a78bfa", gc_bonus: 500,
      required: ["session_1", "session_2", "session_3", "dashboard_created", "monitor_created", "slo_created",
                 "session_4", "session_5", "session_6", "notebook_created", "bits_ai_sre",
                 "learning_path", "case_created", "user_invited"],
      special_count: 2 }
  ],

  users: [
    {
      id: "u1",
      name: "Karl Wong",
      email: "karl.kh.wong@hkjc.org.hk",
      title: "IT Manager",
      milestones: {
        dashboard_created:  true,
        monitor_created:    true,
        slo_created:        true,
        notebook_created:   true,
        case_created:       true,
        user_invited:       true,
        bits_ai_sre:        true,
        session_1:          true,
        session_2:          true,
        session_3:          true,
        session_4:          true,
        session_5:          true,
        session_6:          true,
        learning_path:      true,
        cert_fundamentals:  true,
        cert_apm:           true,
        cert_logs:          false,
        dbm_active:         true,
        profiling_active:   false,
        network_active:     true
      },
      certification: "platinum",
      total_gc: 3850,
      milestone_gc: 3350,
      bonus_gc: 500
    },
    {
      id: "u2",
      name: "David Wong",
      email: "david.sk.wong@hkjc.org.hk",
      title: "Project Champion",
      milestones: {
        dashboard_created:  true,
        monitor_created:    true,
        slo_created:        true,
        notebook_created:   true,
        case_created:       true,
        user_invited:       true,
        bits_ai_sre:        true,
        session_1:          true,
        session_2:          true,
        session_3:          true,
        session_4:          true,
        session_5:          true,
        session_6:          true,
        learning_path:      true,
        cert_fundamentals:  true,
        cert_apm:           false,
        cert_logs:          false,
        dbm_active:         false,
        profiling_active:   true,
        network_active:     true
      },
      certification: "platinum",
      total_gc: 3350,
      milestone_gc: 2850,
      bonus_gc: 500
    },
    {
      id: "u3",
      name: "Ben Cheung",
      email: "ben.wl.cheung@hkjc.org.hk",
      title: "Senior Engineer",
      milestones: {
        dashboard_created:  true,
        monitor_created:    true,
        slo_created:        true,
        notebook_created:   true,
        case_created:       true,
        user_invited:       false,
        bits_ai_sre:        true,
        session_1:          true,
        session_2:          true,
        session_3:          true,
        session_4:          true,
        session_5:          true,
        session_6:          true,
        learning_path:      false,
        cert_fundamentals:  false,
        cert_apm:           false,
        cert_logs:          false,
        dbm_active:         false,
        profiling_active:   false,
        network_active:     false
      },
      certification: "gold",
      total_gc: 1900,
      milestone_gc: 1500,
      bonus_gc: 400
    },
    {
      id: "u4",
      name: "Claude Ducharme",
      email: "claude.ducharme@hkjc.org.hk",
      title: "Platform Architect",
      milestones: {
        dashboard_created:  true,
        monitor_created:    true,
        slo_created:        true,
        notebook_created:   true,
        case_created:       true,
        user_invited:       true,
        bits_ai_sre:        false,
        session_1:          true,
        session_2:          true,
        session_3:          true,
        session_4:          true,
        session_5:          true,
        session_6:          true,
        learning_path:      false,
        cert_fundamentals:  false,
        cert_apm:           false,
        cert_logs:          false,
        dbm_active:         false,
        profiling_active:   false,
        network_active:     false
      },
      certification: "silver",
      total_gc: 1700,
      milestone_gc: 1400,
      bonus_gc: 300
    },
    {
      id: "u5",
      name: "Vivian Tam",
      email: "viviantam@vsceptre.com",
      title: "Implementation Lead",
      milestones: {
        dashboard_created:  true,
        monitor_created:    true,
        slo_created:        false,
        notebook_created:   true,
        case_created:       true,
        user_invited:       false,
        bits_ai_sre:        false,
        session_1:          true,
        session_2:          true,
        session_3:          true,
        session_4:          false,
        session_5:          false,
        session_6:          false,
        learning_path:      false,
        cert_fundamentals:  false,
        cert_apm:           false,
        cert_logs:          false,
        dbm_active:         false,
        profiling_active:   false,
        network_active:     false
      },
      certification: "bronze",
      total_gc: 1000,
      milestone_gc: 800,
      bonus_gc: 200
    },
    {
      id: "u6",
      name: "Kaman Ng",
      email: "kaman@vsceptre.com",
      title: "DevOps Engineer",
      milestones: {
        dashboard_created:  true,
        monitor_created:    true,
        slo_created:        false,
        notebook_created:   false,
        case_created:       false,
        user_invited:       false,
        bits_ai_sre:        false,
        session_1:          true,
        session_2:          true,
        session_3:          true,
        session_4:          false,
        session_5:          false,
        session_6:          false,
        learning_path:      false,
        cert_fundamentals:  false,
        cert_apm:           false,
        cert_logs:          false,
        dbm_active:         false,
        profiling_active:   false,
        network_active:     false
      },
      certification: "bronze",
      total_gc: 800,
      milestone_gc: 600,
      bonus_gc: 200
    },
    {
      id: "u7",
      name: "Sarah Chen",
      email: "sarah.chen@hkjc.org.hk",
      title: "QA Engineer",
      milestones: {
        dashboard_created:  true,
        monitor_created:    true,
        slo_created:        false,
        notebook_created:   false,
        case_created:       false,
        user_invited:       false,
        bits_ai_sre:        false,
        session_1:          true,
        session_2:          false,
        session_3:          false,
        session_4:          false,
        session_5:          false,
        session_6:          false,
        learning_path:      false,
        cert_fundamentals:  false,
        cert_apm:           false,
        cert_logs:          false,
        dbm_active:         false,
        profiling_active:   false,
        network_active:     false
      },
      certification: "bronze",
      total_gc: 600,
      milestone_gc: 400,
      bonus_gc: 200
    },
    {
      id: "u8",
      name: "Thomas Fong",
      email: "thomas.fong@hkjc.org.hk",
      title: "Infrastructure Lead",
      milestones: {
        dashboard_created:  true,
        monitor_created:    false,
        slo_created:        false,
        notebook_created:   false,
        case_created:       false,
        user_invited:       false,
        bits_ai_sre:        false,
        session_1:          true,
        session_2:          false,
        session_3:          false,
        session_4:          false,
        session_5:          false,
        session_6:          false,
        learning_path:      false,
        cert_fundamentals:  false,
        cert_apm:           false,
        cert_logs:          false,
        dbm_active:         false,
        profiling_active:   false,
        network_active:     false
      },
      certification: null,
      total_gc: 250,
      milestone_gc: 250,
      bonus_gc: 0
    }
  ]
};
