/* =========================================================
   Datadog Adoption Scorecard — script.js

   Data source priority:
   1. LOCAL SERVER mode  — fetches /api/data (live, auto-refreshes)
   2. STATIC / tiiny.host — window.DD_DATA (from data.js generated by refresh.js)
   3. DEMO fallback      — window.DD_SAMPLE_DATA (from data.sample.js)
   ========================================================= */

'use strict';

// ─── Detect mode ────────────────────────────────────────────────────────────
// Use server API for any http(s):// origin (localhost dev OR production GCP)
// Only use static/fallback mode for file:// (direct file open without a server)
const IS_LOCAL_SERVER = (
  typeof location !== 'undefined' &&
  /^https?:\/\//.test(location.origin)
);

let DATA      = null;
let IS_SAMPLE = false;

// ─── Admin PIN state ─────────────────────────────────────────────────────────
let isAdminMode = sessionStorage.getItem('adminMode') === 'true';

function toggleAdminLock() {
  if (isAdminMode) {
    isAdminMode = false;
    sessionStorage.removeItem('adminMode');
    updateLockIcon();
    refreshGridBody();
  } else {
    openPinModal();
  }
}

function openPinModal() {
  document.getElementById('pin-backdrop').classList.add('open');
  document.getElementById('pin-modal').classList.add('open');
  document.getElementById('pin-error').textContent = '';
  document.getElementById('pin-input').value = '';
  setTimeout(() => document.getElementById('pin-input').focus(), 50);
}

function closePinModal() {
  document.getElementById('pin-backdrop').classList.remove('open');
  document.getElementById('pin-modal').classList.remove('open');
}

function submitPin() {
  const pin = document.getElementById('pin-input').value.trim();
  if (!pin) return;
  fetch('/api/verify-pin', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ pin })
  })
  .then(r => r.json())
  .then(({ valid }) => {
    if (valid) {
      isAdminMode = true;
      sessionStorage.setItem('adminMode', 'true');
      closePinModal();
      updateLockIcon();
      refreshGridBody();
    } else {
      document.getElementById('pin-error').textContent = 'Incorrect PIN — try again';
      document.getElementById('pin-input').value = '';
      document.getElementById('pin-input').focus();
    }
  })
  .catch(() => {
    document.getElementById('pin-error').textContent = 'Could not verify PIN';
  });
}

function updateLockIcon() {
  const btn = document.getElementById('btn-admin-lock');
  if (!btn) return;
  if (isAdminMode) {
    btn.textContent = '🔓';
    btn.title = 'Admin mode ON — click to lock';
    btn.classList.add('unlocked');
  } else {
    btn.textContent = '🔒';
    btn.title = 'Admin mode — click to unlock circle editing';
    btn.classList.remove('unlocked');
  }
}

// ─── Boot ───────────────────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  if (IS_LOCAL_SERVER) {
    bootFromServer();
  } else {
    bootFromStatic();
  }
});

// Poll server for data; once received, render
function bootFromServer() {
  showLoadingState('Fetching live data from Datadog…');
  setFetchIndicator(true);
  fetchServerData();
  // Auto-poll server status to keep "last updated" fresh
  setInterval(fetchServerData, 30 * 1000); // re-fetch every 30 sec — keeps all viewers in sync
}

function fetchServerData() {
  fetch('/api/data')
    .then(r => r.json())
    .then(json => {
      if (json.status === 'refreshing') {
        showLoadingState('First data fetch in progress… retrying in 5s');
        setTimeout(fetchServerData, 5000);
        return;
      }
      DATA      = json;
      IS_SAMPLE = false;
      setFetchIndicator(false);
      // In server mode, overrides.json is the source of truth — no localStorage needed
      renderAll();
    })
    .catch(err => {
      console.warn('Server fetch failed:', err);
      fallbackToStatic();
    });
}

// ─── localStorage helpers for static/tiiny.host mode ────────────────────────
const LS_KEY = 'dd_scorecard_manual_overrides';

function loadLocalOverrides() {
  try { return JSON.parse(localStorage.getItem(LS_KEY) || '{}'); } catch (_) { return {}; }
}

function saveLocalOverride(email, milestoneId, value) {
  try {
    const stored = loadLocalOverrides();
    if (!stored[email]) stored[email] = {};
    stored[email][milestoneId] = value;
    localStorage.setItem(LS_KEY, JSON.stringify(stored));
  } catch (_) { /* storage full or unavailable */ }
}

function applyLocalOverridesToData(data) {
  if (!data || !data.users) return;
  const stored = loadLocalOverrides();
  for (const [email, milestones] of Object.entries(stored)) {
    const user = data.users.find(u => u.email === email);
    if (!user) continue;
    for (const [msId, val] of Object.entries(milestones)) {
      user.milestones[msId] = val;
    }
  }
}

function bootFromStatic() {
  if (window.DD_DATA && window.DD_DATA.users) {
    DATA      = window.DD_DATA;
    IS_SAMPLE = false;
  } else if (window.DD_SAMPLE_DATA && window.DD_SAMPLE_DATA.users) {
    DATA      = window.DD_SAMPLE_DATA;
    IS_SAMPLE = true;
  }
  if (!DATA) {
    document.body.innerHTML = '<div style="padding:40px;color:#f66;font-family:monospace">No data found. Run <code>node refresh.js</code> or <code>node server.js</code>.</div>';
    return;
  }
  // Restore any manual overrides saved in localStorage (static/tiiny.host mode)
  if (!IS_LOCAL_SERVER) applyLocalOverridesToData(DATA);
  renderAll();
}

function fallbackToStatic() {
  DATA      = window.DD_DATA?.users ? window.DD_DATA : window.DD_SAMPLE_DATA;
  IS_SAMPLE = !window.DD_DATA?.users;
  if (DATA) renderAll();
}

function showLoadingState(msg) {
  const banner = document.getElementById('demo-banner');
  if (banner) { banner.textContent = '⏳ ' + msg; banner.classList.add('visible'); }
}

function setFetchIndicator(visible) {
  const el = document.getElementById('hdr-fetch-status');
  if (el) el.style.display = visible ? 'inline-flex' : 'none';
}

function renderAll() {
  if (!DATA) return;

  // Hide loading / update demo banner
  const banner = document.getElementById('demo-banner');
  if (banner) {
    if (IS_SAMPLE) {
      banner.textContent = '🎯 DEMO MODE — Run node refresh.js or node server.js to load live data.';
      banner.classList.add('visible');
    } else if (IS_LOCAL_SERVER) {
      banner.textContent = `🟢 Live data via server.js — auto-refreshes every 30 min`;
      banner.classList.add('visible', 'live');
    } else {
      banner.classList.remove('visible');
    }
  }

  // Header meta
  document.getElementById('hdr-org-name').textContent = DATA.meta.org_name;
  document.getElementById('hdr-last-updated').textContent = formatDate(DATA.meta.last_updated);

  updateLockIcon();
  renderGrid();
  renderAwardsPanel();
  renderScoreboard();
}

// ─── View switching ──────────────────────────────────────────────────────────
function showView(name) {
  document.querySelectorAll('.view').forEach(v => v.classList.remove('active'));
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  document.getElementById('view-' + name).classList.add('active');
  document.getElementById('tab-' + name).classList.add('active');
}

// ─── Utilities ───────────────────────────────────────────────────────────────
function formatDate(iso) {
  if (!iso) return '—';
  try {
    const d = new Date(iso);
    return d.toLocaleString('en-HK', { dateStyle: 'medium', timeStyle: 'short' });
  } catch { return iso; }
}

/** Stable color from string hash */
function stringColor(str) {
  const PALETTE = [
    '#e53e3e','#dd6b20','#d69e2e','#38a169','#319795',
    '#3182ce','#6b46c1','#d53f8c','#2b6cb0','#285e61',
    '#744210','#276749','#1a365d','#44337a','#702459'
  ];
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
  return PALETTE[h % PALETTE.length];
}

/** Two-letter initials from name */
function initials(name) {
  const parts = name.trim().split(/\s+/);
  if (parts.length >= 2) return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
  return name.slice(0, 2).toUpperCase();
}

/** Total milestone count across all sections */
// Org milestones are org-wide context only — excluded from individual scoring
const INDIVIDUAL_SECTIONS = ['core', 'day1', 'day2', 'self_learning', 'advance'];

function totalMilestoneCount() {
  const m = DATA.milestones;
  return INDIVIDUAL_SECTIONS.reduce((n, s) => n + (m[s]?.length || 0), 0);
}

/** Count completed individual milestones for a user (excludes org) */
function completedCount(user) {
  const m = DATA.milestones;
  return INDIVIDUAL_SECTIONS.flatMap(s => m[s] || [])
    .filter(ms => user.milestones[ms.id]).length;
}

/** Completion percentage for a user */
function completionPct(user) {
  return Math.round((completedCount(user) / totalMilestoneCount()) * 100);
}

/** Certification tier label/icon for a user */
function certLabel(certId) {
  const tier = DATA.certification_tiers.find(t => t.id === certId);
  return tier ? { icon: tier.icon, name: tier.name, color: tier.color } : { icon: '—', name: 'None', color: '#555' };
}

// ─── Avatar element ──────────────────────────────────────────────────────────
function makeAvatar(user, size = 42) {
  const el = document.createElement('div');
  el.className = 'user-avatar';
  el.style.width  = size + 'px';
  el.style.height = size + 'px';
  el.style.fontSize = Math.round(size * 0.33) + 'px';
  el.style.background = stringColor(user.email);
  el.textContent = initials(user.name);
  return el;
}

// ─── GRID RENDERING ──────────────────────────────────────────────────────────
// ─── Org Status Bar ──────────────────────────────────────────────────────────
function renderOrgStatus() {
  const bar = document.getElementById('org-status-bar');
  if (!bar) return;
  bar.innerHTML = '';

  const m = DATA.milestones;
  const anyUser = DATA.users[0]; // org milestones are identical for all users

  // Helper: build one chip
  function makeChip(ms) {
    const passed = anyUser ? !!(anyUser.milestones || {})[ms.id] : false;
    const chip = document.createElement('button');
    chip.className = 'org-chip ' + (passed ? 'org-chip-pass' : 'org-chip-fail');
    chip.title = 'Click to see evidence';
    chip.innerHTML = `${ms.icon} ${ms.name} <span class="org-chip-status">${passed ? '✅' : '❌'}</span>`;
    chip.addEventListener('click', () => {
      if (anyUser) showEvidenceModal(anyUser, ms);
    });
    return chip;
  }

  // Org-level section
  const orgLabel = document.createElement('span');
  orgLabel.className = 'org-bar-label';
  orgLabel.textContent = 'Org Foundation';
  bar.appendChild(orgLabel);

  m.org.forEach(ms => bar.appendChild(makeChip(ms)));

  const sep = document.createElement('span');
  sep.className = 'org-bar-sep';
  bar.appendChild(sep);

  // Special achievements section
  const spLabel = document.createElement('span');
  spLabel.className = 'org-bar-label';
  spLabel.textContent = 'Special Achievements';
  bar.appendChild(spLabel);

  m.special.forEach(ms => bar.appendChild(makeChip(ms)));
}

// ─── Grid state ──────────────────────────────────────────────────────────────
let gridFilter = 'all';
let gridSearch = '';
let gridSort   = 'gc';

function renderGrid() {
  const container = document.getElementById('cert-grid-container');
  container.innerHTML = '';

  // ── Controls ──
  const controls = document.createElement('div');
  controls.className = 'grid-controls';
  controls.innerHTML = `
    <input class="grid-search" id="grid-search" type="search" placeholder="🔍  Search champion…">
    <div class="cert-filters" id="cert-filters">
      <button class="cert-filter active" data-f="all">All</button>
      <button class="cert-filter" data-f="none">⬜ None</button>
      <button class="cert-filter" data-f="bronze">🥉</button>
      <button class="cert-filter" data-f="silver">🥈</button>
      <button class="cert-filter" data-f="gold">🥇</button>
      <button class="cert-filter" data-f="platinum">💎</button>
    </div>
    <div class="sort-controls">
      <span class="sort-label">Sort:</span>
      <button class="sort-btn active" data-s="gc">GC</button>
      <button class="sort-btn" data-s="pct">Progress</button>
      <button class="sort-btn" data-s="name">Name</button>
    </div>
  `;
  container.appendChild(controls);

  // Wire controls
  controls.querySelector('#grid-search').addEventListener('input', e => {
    gridSearch = e.target.value;
    refreshGridBody();
  });
  controls.querySelectorAll('.cert-filter').forEach(btn => {
    btn.addEventListener('click', () => {
      gridFilter = btn.dataset.f;
      controls.querySelectorAll('.cert-filter').forEach(b => b.classList.toggle('active', b.dataset.f === gridFilter));
      refreshGridBody();
    });
  });
  controls.querySelectorAll('.sort-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      gridSort = btn.dataset.s;
      controls.querySelectorAll('.sort-btn').forEach(b => b.classList.toggle('active', b.dataset.s === gridSort));
      refreshGridBody();
    });
  });

  // ── Table wrapper ──
  const wrap = document.createElement('div');
  wrap.className = 'fg-wrap';
  wrap.id = 'fg-wrap';
  container.appendChild(wrap);

  refreshGridBody();
}

function refreshGridBody() {
  const wrap = document.getElementById('fg-wrap');
  if (!wrap) return;
  wrap.innerHTML = '';

  const m = DATA.milestones;
  const users = getSortedFilteredUsers();

  // Milestone columns: core, day1, day2, self_learning, advance (with separators between)
  const colSections = [
    { items: m.core,          cls: 'fg-col-core',          label: 'CORE — Audit Trail' },
    { items: m.day1,          cls: 'fg-col-day1',          label: 'HKJC Day 1' },
    { items: m.day2,          cls: 'fg-col-day2',          label: 'HKJC Day 2' },
    { items: m.self_learning, cls: 'fg-col-self-learning', label: 'Self Learning' },
    { items: m.advance,       cls: 'fg-col-advance',       label: 'ADVANCED — Certifications' },
  ];
  const allCols = colSections.flatMap((s, si) =>
    s.items.map((ms, mi) => ({ ms, cls: s.cls, firstInSection: mi === 0, sectionLabel: s.label, isLast: si === colSections.length - 1 }))
  );

  const table = document.createElement('table');
  table.className = 'fg-table';

  // === THEAD ===
  const thead = document.createElement('thead');

  // Section label row
  const labelRow = document.createElement('tr');
  const cornerBlank = document.createElement('th');
  cornerBlank.className = 'fg-corner fg-sticky-col';
  cornerBlank.rowSpan = 2;
  cornerBlank.innerHTML = `<span class="fg-champion-count">${users.length} champion${users.length !== 1 ? 's' : ''}</span>`;
  labelRow.appendChild(cornerBlank);

  colSections.forEach((s, si) => {
    const th = document.createElement('th');
    th.colSpan = s.items.length;
    th.className = 'fg-section-label ' + s.cls;
    th.textContent = s.label;
    labelRow.appendChild(th);
    if (si < colSections.length - 1) {
      const sep = document.createElement('th');
      sep.className = 'fg-col-sep-header';
      sep.rowSpan = 2;
      labelRow.appendChild(sep);
    }
  });

  const progTh = document.createElement('th');
  progTh.className = 'fg-progress-hdr';
  progTh.rowSpan = 2;
  progTh.textContent = 'Progress';
  labelRow.appendChild(progTh);

  const gcTh = document.createElement('th');
  gcTh.className = 'fg-gc-hdr';
  gcTh.rowSpan = 2;
  gcTh.textContent = 'GC Earned';
  labelRow.appendChild(gcTh);

  thead.appendChild(labelRow);

  // Milestone icon row
  const msRow = document.createElement('tr');
  allCols.forEach(({ ms, cls, firstInSection, isLast }) => {
    const th = document.createElement('th');
    th.className = 'fg-ms-hdr ' + cls;
    th.title = ms.name + ' — ' + ms.points + ' GC\n' + (ms.audit_query || 'Manual override');
    th.textContent = ms.icon;
    msRow.appendChild(th);

    if (!isLast && allCols[allCols.indexOf({ ms, cls, firstInSection, isLast })]?.firstInSection === false) {
      // separators already added in label row
    }
  });
  thead.appendChild(msRow);
  table.appendChild(thead);

  // === TBODY ===
  const tbody = document.createElement('tbody');

  if (users.length === 0) {
    const emptyRow = document.createElement('tr');
    const emptyTd = document.createElement('td');
    emptyTd.colSpan = allCols.length + 4;
    emptyTd.className = 'fg-empty';
    emptyTd.textContent = 'No champions match the current filter.';
    emptyRow.appendChild(emptyTd);
    tbody.appendChild(emptyRow);
  } else {
    users.forEach((user, idx) => {
      tbody.appendChild(buildFGRow(user, idx + 1, allCols, colSections));
    });
  }

  table.appendChild(tbody);
  wrap.appendChild(table);
}

function buildFGRow(user, rank, allCols, colSections) {
  const pct = completionPct(user);
  const c   = certLabel(user.certification);
  const row = document.createElement('tr');
  row.className = 'fg-user-row';
  row.dataset.email = user.email;

  // ── User info cell (sticky) ──
  const userTd = document.createElement('td');
  userTd.className = 'fg-user-cell fg-sticky-col';
  userTd.innerHTML = `
    <div class="fg-user-inner">
      <div class="fg-avatar" style="background:${stringColor(user.email)}">${initials(user.name)}</div>
      <div class="fg-name-wrap">
        <div class="fg-name">${user.name}</div>
        <div class="fg-cert-label" style="color:${c.color}">${c.icon} ${c.name}</div>
      </div>
    </div>`;
  row.appendChild(userTd);

  // ── Milestone cells ──
  let secIdx = 0;
  allCols.forEach(({ ms, cls, firstInSection }, colIdx) => {
    // Section separator column
    if (firstInSection && colIdx > 0) {
      const sepTd = document.createElement('td');
      sepTd.className = 'fg-col-sep';
      row.appendChild(sepTd);
    }

    const done  = !!(user.milestones || {})[ms.id];
    const td    = document.createElement('td');
    td.className = 'fg-cell ' + cls + (done ? ' fg-done' : ' fg-todo');

    if (done) {
      td.textContent = '✓';
    } else if (ms.type === 'manual') {
      td.textContent = '○';
      if (isAdminMode) {
        td.classList.add('fg-manual');
        td.title = 'Click to mark done — ' + ms.name;
        td.addEventListener('click', () => {
          user.milestones[ms.id] = true;
          td.textContent = '✓';
          td.classList.replace('fg-todo', 'fg-done');
          td.classList.remove('fg-manual');
          recalculateUser(user);
          updateFGRowStats(row, user);
          renderScoreboard();
          if (IS_LOCAL_SERVER) {
            fetch('/api/manual-override', { method: 'POST', headers: {'Content-Type':'application/json'},
              body: JSON.stringify({ email: user.email, milestone_id: ms.id, value: true }) }).catch(() => {});
          } else {
            saveLocalOverride(user.email, ms.id, true);
          }
        });
      } else {
        td.title = ms.name + ' — unlock admin mode to edit';
      }
    } else {
      td.innerHTML = '<span class="fg-lock">🔒</span>';
    }

    // Click for evidence modal (non-manual: single click; manual: shift+click)
    td.addEventListener('click', e => {
      if (ms.type !== 'manual' || e.shiftKey) showEvidenceModal(user, ms);
    });
    td.addEventListener('contextmenu', e => { e.preventDefault(); showEvidenceModal(user, ms); });

    row.appendChild(td);
  });

  // ── Progress cell ──
  const progTd = document.createElement('td');
  progTd.className = 'fg-progress-cell';
  progTd.innerHTML = `
    <div class="fg-bar-bg"><div class="fg-bar-fill" style="width:${pct}%"></div></div>
    <div class="fg-pct">${pct}%</div>`;
  row.appendChild(progTd);

  // ── GC cell ──
  const gcTd = document.createElement('td');
  gcTd.className = 'fg-gc-cell';
  gcTd.textContent = user.total_gc.toLocaleString();
  row.appendChild(gcTd);

  return row;
}

function updateFGRowStats(row, user) {
  const pct  = completionPct(user);
  const c    = certLabel(user.certification);
  const fill = row.querySelector('.fg-bar-fill');
  const pctEl = row.querySelector('.fg-pct');
  const gcEl  = row.querySelector('.fg-gc-cell');
  const certEl = row.querySelector('.fg-cert-label');
  if (fill)   fill.style.width = pct + '%';
  if (pctEl)  pctEl.textContent = pct + '%';
  if (gcEl)   gcEl.textContent  = user.total_gc.toLocaleString();
  if (certEl) { certEl.textContent = c.icon + ' ' + c.name; certEl.style.color = c.color; }
}

function getSortedFilteredUsers() {
  let users = [...DATA.users];
  if (gridFilter !== 'all') users = users.filter(u => (u.certification || 'none') === gridFilter);
  if (gridSearch) {
    const q = gridSearch.toLowerCase();
    users = users.filter(u => u.name.toLowerCase().includes(q) || u.email.toLowerCase().includes(q));
  }
  if (gridSort === 'gc')   users.sort((a, b) => b.total_gc - a.total_gc);
  if (gridSort === 'pct')  users.sort((a, b) => completionPct(b) - completionPct(a));
  if (gridSort === 'name') users.sort((a, b) => a.name.localeCompare(b.name));
  return users;
}

// ─── Toggle manual cell (kept for backward compat; new grid handles inline) ──
function toggleManualCell(user, ms, td) {
  const newVal = !user.milestones[ms.id];
  user.milestones[ms.id] = newVal;
  td.classList.toggle('done', newVal);
  td.classList.toggle('not-done', !newVal);
  td.textContent = newVal ? '✓' : '';
  recalculateUser(user);
  renderScoreboard();
  // Update row stats in new flipped grid
  const row = document.querySelector(`.fg-user-row[data-email="${user.email}"]`);
  if (row) updateFGRowStats(row, user);
}

function recalculateUser(user) {
  // Org milestones excluded — individual scoring only
  const allMs = INDIVIDUAL_SECTIONS.flatMap(s => DATA.milestones[s] || []);

  let gc = 0;
  allMs.forEach(ms => {
    if (user.milestones[ms.id]) gc += ms.points;
  });

  // Bonus GC from certification
  let cert = null;
  let bonus = 0;
  const tiers = [...DATA.certification_tiers].reverse(); // check from highest

  for (const tier of tiers) {
    const hasAll = tier.required.every(id => user.milestones[id]);
    if (hasAll) {
      cert = tier.id;
      bonus = tier.gc_bonus;
      break;
    }
  }

  user.certification  = cert;
  user.milestone_gc   = gc;
  user.bonus_gc       = bonus;
  user.total_gc       = gc + bonus;
}

function refreshUserCertBadge(user) {
  const row = document.querySelector(`.fg-user-row[data-email="${user.email}"]`);
  if (row) updateFGRowStats(row, user);
  // Legacy no-op kept so old call sites don't break
  const idx = DATA.users.indexOf(user);
  if (idx < 0) return;
  const badges = document.querySelectorAll('.user-cert-badge');
  if (badges[idx]) {
    const c = certLabel(user.certification);
    badges[idx].textContent = c.icon;
    badges[idx].title = c.name + ' — ' + user.total_gc + ' GC';
  }
}

// ─── Tooltip ─────────────────────────────────────────────────────────────────
function showTooltip(e, ms, user, done) {
  const tip = document.getElementById('tooltip');
  tip.innerHTML = `
    <div class="tooltip-name">${ms.icon} ${ms.name}</div>
    <div class="tooltip-pts">${ms.points} GC</div>
    <div class="tooltip-type">${typeLabel(ms.type)} · ${done ? '✅ Completed' : '⬜ Not done'}</div>
    <div class="tooltip-type">${user.name}</div>
  `;
  tip.classList.add('visible');
  positionTooltip(e);
}

function positionTooltip(e) {
  const tip = document.getElementById('tooltip');
  const x = e.clientX + 14;
  const y = e.clientY + 14;
  const maxX = window.innerWidth - 240;
  const maxY = window.innerHeight - 120;
  tip.style.left = Math.min(x, maxX) + 'px';
  tip.style.top  = Math.min(y, maxY) + 'px';
}

function hideTooltip() {
  document.getElementById('tooltip').classList.remove('visible');
}

function typeLabel(type) {
  switch (type) {
    case 'audit':  return 'Auto · Audit Trail';
    case 'metric': return 'Auto · Usage Metric';
    case 'manual': return 'Manual · overrides.json';
    case 'special':return 'Auto · Special Achievement';
    default: return type;
  }
}

// ─── AWARDS PANEL ────────────────────────────────────────────────────────────
// ─── Awards config — prizes attached to each cert tier ───────────────────────
const TIER_PRIZES = {
  bronze:   {
    name:   'Bronze',
    prize:  'Datadog Sticker Pack', emoji: '🎁',
    bullets: ['Attend Session 1 (Observability Overview)', 'Create a Dashboard', 'Configure an Alert'],
    prefix:  'Complete all of:',
  },
  silver:   {
    name:   'Silver',
    prize:  'Datadog T-Shirt', emoji: '👕',
    bullets: ['Complete all 3 Day 1 sessions', 'Create your first SLO'],
    prefix:  'Bronze, plus:',
  },
  gold:     {
    name:   'Gold',
    prize:  'Datadog Hoodie', emoji: '🧥',
    bullets: ['Complete all 3 Day 2 sessions', 'Write a Notebook', 'Trigger a Bits AI SRE Investigation'],
    prefix:  'Silver, plus:',
  },
  platinum: {
    name:   'Platinum',
    prize:  '$50 Gift Card', emoji: '💳',
    bullets: ['Complete a Persona Based Learning Path', 'Create a Case', 'Invite a Team Member to Datadog'],
    prefix:  'Gold, plus:',
  },
};

const SPECIAL_PRIZES = [
  { icon: '🏆', label: 'First to reach Platinum',        prize: 'Exclusive Datadog Backpack' },
  { icon: '🤖', label: 'First Bits AI SRE Investigation', prize: 'Bits AI Collector\'s Badge'  },
  { icon: '📊', label: 'Top GC Earner',                  prize: '$100 Gift Voucher'           },
];

function renderAwardsPanel() {
  const panel = document.getElementById('awards-panel');
  panel.innerHTML = '';

  // ── Title ──
  panel.innerHTML = `<div class="awards-title">🏆 Awards & Prizes</div>`;

  // ── Progress summary ──
  const users = DATA.users || [];
  const certCounts = { bronze: 0, silver: 0, gold: 0, platinum: 0 };
  users.forEach(u => { if (u.certification) certCounts[u.certification] = (certCounts[u.certification] || 0) + 1; });
  const certified = Object.values(certCounts).reduce((a,b)=>a+b,0);

  const summary = document.createElement('div');
  summary.className = 'awards-summary';
  summary.innerHTML = `
    <span class="awards-summary-num">${certified}</span>
    <span class="awards-summary-lbl">of ${users.length} certified</span>
  `;
  panel.appendChild(summary);

  // ── Cert tier cards ──
  const sectionLabel = document.createElement('div');
  sectionLabel.className = 'awards-section-label';
  sectionLabel.textContent = 'CERTIFICATION TIERS';
  panel.appendChild(sectionLabel);

  const allMs = INDIVIDUAL_SECTIONS.flatMap(s => DATA.milestones[s] || []);

  DATA.certification_tiers.forEach(tier => {
    const p           = TIER_PRIZES[tier.id] || { name: tier.id, prize: '', emoji: '🎁', bullets: [], prefix: 'Complete:' };
    const tierName    = p.name || tier.name || (tier.id.charAt(0).toUpperCase() + tier.id.slice(1));
    const earnedCount = certCounts[tier.id] || 0;
    const bulletHtml  = p.bullets.map(b => `<li>${b}</li>`).join('');

    const card = document.createElement('div');
    card.className = 'tier-card tier-card-' + tier.id;
    card.innerHTML = `
      <div class="tier-card-header">
        <span class="tier-icon">${tier.icon}</span>
        <div class="tier-card-info">
          <span class="tier-name" style="color:${tier.color}">${tierName}</span>
          <span class="tier-prize">${p.emoji} ${p.prize}</span>
        </div>
        <span class="tier-gc" style="color:${tier.color}">+${tier.gc_bonus} GC</span>
      </div>
      <div class="tier-reqs-label">${p.prefix}</div>
      <ul class="tier-bullets">${bulletHtml}</ul>
      <div class="tier-progress">
        <span class="tier-earned" style="color:${tier.color}">${earnedCount} champion${earnedCount!==1?'s':''} earned</span>
      </div>
    `;
    panel.appendChild(card);
  });

  // ── Special prizes ──
  const specLabel = document.createElement('div');
  specLabel.className = 'awards-section-label';
  specLabel.style.marginTop = '16px';
  specLabel.textContent = 'SPECIAL PRIZES';
  panel.appendChild(specLabel);

  // Compute first Platinum and first Bits AI SRE
  const platinumUsers = users.filter(u => u.certification === 'platinum');
  const bitsAiUsers   = users.filter(u => u.milestones?.bits_ai_sre);
  const topGCUser     = users.length > 0 ? users.reduce((a,b) => b.total_gc > a.total_gc ? b : a) : null;

  SPECIAL_PRIZES.forEach((sp, i) => {
    let winner = null;
    if (i === 0) winner = platinumUsers[0];
    if (i === 1) winner = bitsAiUsers[0];
    if (i === 2) winner = topGCUser;

    const item = document.createElement('div');
    item.className = 'special-prize-card' + (winner ? ' sp-claimed' : '');
    item.innerHTML = `
      <div class="sp-header">
        <span class="sp-icon">${sp.icon}</span>
        <div class="sp-info">
          <div class="sp-label">${sp.label}</div>
          <div class="sp-prize">🎁 ${sp.prize}</div>
        </div>
      </div>
      ${winner
        ? `<div class="sp-winner">
             <div class="sp-avatar" style="background:${stringColor(winner.email)}">${initials(winner.name)}</div>
             <span class="sp-winner-name">${winner.name}</span>
           </div>`
        : `<div class="sp-unclaimed">Not yet claimed</div>`
      }
    `;
    panel.appendChild(item);
  });
}

// ─── GC breakdown by category ────────────────────────────────────────────────
function gcBreakdown(user) {
  const ms = user.milestones || {};
  const calc = (items) => (items || []).reduce((sum, m) => sum + (ms[m.id] ? m.points : 0), 0);
  return {
    core:    calc(DATA.milestones.core),
    manual:  calc([...(DATA.milestones.day1||[]), ...(DATA.milestones.day2||[]), ...(DATA.milestones.self_learning||[])]),
    advance: calc(DATA.milestones.advance),
    bonus:   user.bonus_gc || 0,
  };
}

// ─── SCOREBOARD ──────────────────────────────────────────────────────────────
function renderScoreboard() {
  const container = document.getElementById('scoreboard-container');
  container.innerHTML = '';
  container.style.padding = '24px';

  const users = [...DATA.users].sort((a, b) => b.total_gc - a.total_gc);
  const total  = totalMilestoneCount();

  // ── Stats row ──
  const statsRow = document.createElement('div');
  statsRow.className = 'stats-row';

  const platCount   = users.filter(u => u.certification === 'platinum').length;
  const goldCount   = users.filter(u => u.certification === 'gold').length;
  const totalGC     = users.reduce((s, u) => s + u.total_gc, 0);
  const certCount   = users.filter(u => u.certification).length;

  const stats = [
    { label: 'Champions',       value: users.length,  cls: 'blue' },
    { label: 'Certified',       value: certCount,      cls: 'green' },
    { label: 'Platinum',        value: platCount,      cls: 'purple' },
    { label: 'Total GC Awarded',value: totalGC.toLocaleString() + ' GC', cls: 'gold' },
  ];

  stats.forEach(s => {
    const card = document.createElement('div');
    card.className = 'stat-card ' + s.cls;
    card.innerHTML = `<div class="stat-value">${s.value}</div><div class="stat-label">${s.label}</div>`;
    statsRow.appendChild(card);
  });

  container.appendChild(statsRow);

  // ── GC Category Legend ──
  const legend = document.createElement('div');
  legend.className = 'gc-legend';
  legend.innerHTML = `
    <span class="gc-legend-title">GC Points by category:</span>
    <span class="gc-lbl gc-lbl-core">📋 Core <span class="gc-legend-desc">— Audit Trail: dashboards, monitors, SLOs, notebooks, cases, Bits AI SRE</span></span>
    <span class="gc-lbl gc-lbl-manual">✍️ Manual <span class="gc-legend-desc">— Enablement sessions + Persona learning path</span></span>
    <span class="gc-lbl gc-lbl-advance">📜 Advance <span class="gc-legend-desc">— Datadog certifications (500 GC each)</span></span>
    <span class="gc-lbl gc-lbl-bonus">🏅 Cert Bonus <span class="gc-legend-desc">— Bronze +200 · Silver +300 · Gold +400 · Platinum +500</span></span>
  `;
  container.appendChild(legend);

  // ── Grid ──
  const grid = document.createElement('div');
  grid.className = 'scoreboard-grid';

  // Card 1: Champion Rankings
  grid.appendChild(makeRankingsCard(users, total));

  // Card 2: Certified Practitioners
  grid.appendChild(makeCertifiedCard(users));

  // Card 3: Top GC Earners
  grid.appendChild(makeTopGCCard(users));

  container.appendChild(grid);
}

function makeRankingsCard(users, total) {
  const card = document.createElement('div');
  card.className = 'score-card';
  card.innerHTML = `<div class="score-card-title">🥇 Champion Rankings</div>`;

  users.forEach((user, idx) => {
    const pct  = completionPct(user);
    const rank = idx + 1;
    const c    = certLabel(user.certification);

    let rankHtml = '';
    if (rank === 1)      rankHtml = `<span class="champion-rank top1">🥇</span>`;
    else if (rank === 2) rankHtml = `<span class="champion-rank top2">🥈</span>`;
    else if (rank === 3) rankHtml = `<span class="champion-rank top3">🥉</span>`;
    else                 rankHtml = `<span class="champion-rank">#${rank}</span>`;

    const avatarColor = stringColor(user.email);
    const bd = gcBreakdown(user);
    const totalGC = user.total_gc || 0;
    const maxPossible = totalGC || 1;

    // Segment widths as % of total_gc
    const seg = (v) => totalGC > 0 ? Math.round((v / totalGC) * 100) : 0;

    const row = document.createElement('div');
    row.className = 'champion-row';
    row.innerHTML = `
      ${rankHtml}
      <div class="champion-avatar" style="background:${avatarColor};width:34px;height:34px;font-size:12px">
        ${initials(user.name)}
      </div>
      <div class="champion-info">
        <div class="champion-name">${user.name} ${c.icon}</div>
        <div class="gc-breakdown-bar" title="Core: ${bd.core} | Manual: ${bd.manual} | Advance: ${bd.advance} | Cert Bonus: ${bd.bonus}">
          ${bd.core    > 0 ? `<div class="gc-seg gc-seg-core"    style="width:${seg(bd.core)}%"    title="Core: ${bd.core} GC"></div>`       : ''}
          ${bd.manual  > 0 ? `<div class="gc-seg gc-seg-manual"  style="width:${seg(bd.manual)}%"  title="Manual: ${bd.manual} GC"></div>`    : ''}
          ${bd.advance > 0 ? `<div class="gc-seg gc-seg-advance" style="width:${seg(bd.advance)}%" title="Advance: ${bd.advance} GC"></div>`  : ''}
          ${bd.bonus   > 0 ? `<div class="gc-seg gc-seg-bonus"   style="width:${seg(bd.bonus)}%"   title="Cert Bonus: ${bd.bonus} GC"></div>` : ''}
        </div>
        <div class="gc-breakdown-labels">
          ${bd.core    > 0 ? `<span class="gc-lbl gc-lbl-core">📋 ${bd.core}</span>`        : ''}
          ${bd.manual  > 0 ? `<span class="gc-lbl gc-lbl-manual">✍️ ${bd.manual}</span>`   : ''}
          ${bd.advance > 0 ? `<span class="gc-lbl gc-lbl-advance">📜 ${bd.advance}</span>` : ''}
          ${bd.bonus   > 0 ? `<span class="gc-lbl gc-lbl-bonus">🏅 ${bd.bonus}</span>`      : ''}
        </div>
      </div>
      <div class="champion-gc">${totalGC.toLocaleString()}<span class="gc-unit"> GC</span></div>
    `;
    card.appendChild(row);
  });

  return card;
}

function makeCertifiedCard(users) {
  const card = document.createElement('div');
  card.className = 'score-card';
  card.innerHTML = `<div class="score-card-title">🎓 Certified Practitioners</div>`;

  const certified = users.filter(u => u.certification);

  if (certified.length === 0) {
    card.innerHTML += `<div class="empty-state">No certified practitioners yet.</div>`;
    return card;
  }

  // Group by tier (highest first)
  const tierOrder = ['platinum', 'gold', 'silver', 'bronze'];
  tierOrder.forEach(tid => {
    const group = certified.filter(u => u.certification === tid);
    if (group.length === 0) return;

    const t = DATA.certification_tiers.find(t => t.id === tid);
    group.forEach(user => {
      const row = document.createElement('div');
      row.className = 'cert-practitioner';
      row.innerHTML = `
        <span class="cp-badge">${t.icon}</span>
        <div class="cp-avatar" style="
          width:28px;height:28px;border-radius:50%;background:${stringColor(user.email)};
          display:inline-flex;align-items:center;justify-content:center;
          font-size:10px;font-weight:700;color:#fff;flex-shrink:0;margin-right:4px
        ">${initials(user.name)}</div>
        <span class="cp-name">${user.name}</span>
        <span class="cp-level ${tid}">${t.name}</span>
      `;
      card.appendChild(row);
    });
  });

  return card;
}

function makeTopGCCard(users) {
  const card = document.createElement('div');
  card.className = 'score-card';
  card.innerHTML = `<div class="score-card-title">💰 Top GC Earners</div>`;

  users.slice(0, 8).forEach((user, idx) => {
    const c = certLabel(user.certification);
    const maxGC = users[0].total_gc || 1;
    const barW  = Math.round((user.total_gc / maxGC) * 100);

    const bd2 = gcBreakdown(user);
    const row = document.createElement('div');
    row.className = 'champion-row';
    row.innerHTML = `
      <span class="champion-rank" style="font-size:13px;color:#888">#${idx + 1}</span>
      <div class="champion-avatar" style="background:${stringColor(user.email)};width:34px;height:34px;font-size:12px">
        ${initials(user.name)}
      </div>
      <div class="champion-info">
        <div class="champion-name">${user.name} ${c.icon}</div>
        <div class="gc-breakdown-labels" style="margin-top:2px">
          ${bd2.core    > 0 ? `<span class="gc-lbl gc-lbl-core">📋 ${bd2.core}</span>`        : ''}
          ${bd2.manual  > 0 ? `<span class="gc-lbl gc-lbl-manual">✍️ ${bd2.manual}</span>`   : ''}
          ${bd2.advance > 0 ? `<span class="gc-lbl gc-lbl-advance">📜 ${bd2.advance}</span>` : ''}
          ${bd2.bonus   > 0 ? `<span class="gc-lbl gc-lbl-bonus">🏅 ${bd2.bonus}</span>`      : ''}
        </div>
      </div>
      <div class="champion-bar-wrap">
        <div class="champion-bar-bg">
          <div class="champion-bar-fill" style="width:${barW}%;background:linear-gradient(90deg,#b7791f,#f0b429)"></div>
        </div>
        <div class="champion-bar-pct" style="color:#b7791f">${user.total_gc.toLocaleString()} GC</div>
      </div>
    `;
    card.appendChild(row);
  });

  return card;
}

// ─── Evidence Modal ──────────────────────────────────────────────────────────
function showEvidenceModal(user, ms) {
  const ev = (user.evidence || {})[ms.id];
  const passed = !!(user.milestones || {})[ms.id];

  const backdrop = document.getElementById('ev-backdrop');
  const modal    = document.getElementById('ev-modal');
  const content  = document.getElementById('ev-modal-content');

  let html = `
    <div class="ev-title">${ms.icon} ${ms.name}</div>
    <div class="ev-subtitle">${user.name} &nbsp;·&nbsp; <span style="color:#a0a0c0">${user.email}</span></div>
    <div class="ev-status ${passed ? 'pass' : 'fail'}">
      ${passed ? '✅ Completed' : '❌ Not completed'}
    </div>
    <hr class="ev-divider">
  `;

  if (!ev) {
    html += `<div class="ev-field"><span class="ev-field-label">Detection</span><span class="ev-field-value">No evidence data — re-run <code>node refresh.js</code> or <code>node server.js</code></span></div>`;
  } else if (ev.type === 'audit') {
    html += `
      <div class="ev-field"><span class="ev-field-label">Detection method</span><span class="ev-field-value">Datadog Audit Trail</span></div>
      <div class="ev-field"><span class="ev-field-label">Audit query</span><span class="ev-field-value mono">${ev.query}</span></div>
      <div class="ev-field"><span class="ev-field-label">Events found</span><span class="ev-field-value">${ev.count} in last 1 year</span></div>
      ${ev.last_event_at ? `<div class="ev-field"><span class="ev-field-label">Most recent</span><span class="ev-field-value">${formatDate(ev.last_event_at)}${ev.last_event_name ? ' — ' + ev.last_event_name : ''}</span></div>` : ''}
      <div class="ev-field"><span class="ev-field-label">Checked at</span><span class="ev-field-value">${formatDate(ev.checked_at)}</span></div>
    `;
  } else if (ev.type === 'metric') {
    html += `
      <div class="ev-field"><span class="ev-field-label">Detection method</span><span class="ev-field-value">Usage Metric</span></div>
      <div class="ev-field"><span class="ev-field-label">Metric query</span><span class="ev-field-value mono">max:${ev.metric}{*}</span></div>
      <div class="ev-field"><span class="ev-field-label">Current value</span><span class="ev-field-value">${ev.value !== null ? Number(ev.value).toLocaleString() : '—'} (threshold: &gt; 0)</span></div>
      <div class="ev-field"><span class="ev-field-label">Scope</span><span class="ev-field-value">Org-level — applies to all users</span></div>
      <div class="ev-field"><span class="ev-field-label">Checked at</span><span class="ev-field-value">${formatDate(ev.checked_at)}</span></div>
    `;
  } else if (ev.type === 'manual') {
    html += `
      <div class="ev-field"><span class="ev-field-label">Detection method</span><span class="ev-field-value">Manual override (overrides.json)</span></div>
      <div class="ev-field"><span class="ev-field-label">How to set</span><span class="ev-field-value mono">overrides.json → "${user.email}" → "${ms.id}": true</span></div>
    `;
  }

  // Action buttons
  html += `<div class="ev-actions">`;
  if (ev && ev.verify_url) {
    html += `<a class="ev-btn ev-btn-verify" href="${ev.verify_url}" target="_blank" rel="noopener">🔗 Verify in Datadog ↗</a>`;
  }
  if (ms.type === 'manual') {
    html += `<button class="ev-btn ev-btn-manual" onclick="manualMarkDone('${user.email}','${ms.id}');closeEvidenceModal()">✓ Mark as done</button>`;
  }
  html += `</div>`;

  content.innerHTML = html;
  backdrop.classList.add('open');
  modal.classList.add('open');

  // Close on Escape
  document.addEventListener('keydown', handleModalEsc);
}

function closeEvidenceModal() {
  document.getElementById('ev-backdrop').classList.remove('open');
  document.getElementById('ev-modal').classList.remove('open');
  document.removeEventListener('keydown', handleModalEsc);
}

function handleModalEsc(e) {
  if (e.key === 'Escape') closeEvidenceModal();
}

function manualMarkDone(email, milestoneId) {
  const user = DATA.users.find(u => u.email === email);
  if (!user) return;
  const ms = [...(DATA.milestones.day1||[]), ...(DATA.milestones.day2||[]), ...(DATA.milestones.self_learning||[]), ...(DATA.milestones.advance||[])].find(m => m.id === milestoneId);
  if (!ms) return;
  user.milestones[milestoneId] = true;
  recalculateUser(user);
  renderGrid();
  renderAwardsPanel();
  renderScoreboard();

  if (IS_LOCAL_SERVER) {
    // Server persists to overrides.json automatically
    fetch('/api/manual-override', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email, milestone_id: milestoneId, value: true }),
    }).catch(() => {});
  } else {
    // Static/tiiny.host: save to localStorage so it survives page refresh
    saveLocalOverride(email, milestoneId, true);
  }
}

// ─── Refresh handler ─────────────────────────────────────────────────────────
function handleRefresh() {
  if (IS_LOCAL_SERVER) {
    const btn = document.querySelector('.btn-refresh');
    if (btn) { btn.textContent = '↻ Refresh'; btn.disabled = true; }
    const nowLabel = document.getElementById('hdr-last-updated');
    if (nowLabel) nowLabel.textContent = formatDate(new Date().toISOString());
    setFetchIndicator(true);
    const startedAt = Date.now();
    fetch('/api/refresh', { method: 'POST' })
      .then(() => { waitForRefreshComplete(startedAt, btn); })
      .catch(() => { setFetchIndicator(false); if (btn) { btn.textContent = '↻ Refresh'; btn.disabled = false; } });
  } else if (IS_SAMPLE) {
    alert('You are in demo mode.\n\nTo load live data:\n• Local server: node server.js\n• Static: node refresh.js → reload');
  } else {
    location.reload();
  }
}

// Poll /api/status until the server reports a completed refresh newer than when we triggered it
function waitForRefreshComplete(startedAt, btn) {
  fetch('/api/status')
    .then(r => r.json())
    .then(st => {
      const lastRefreshMs = st.lastRefresh ? new Date(st.lastRefresh).getTime() : 0;
      if (!st.refreshing && lastRefreshMs > startedAt) {
        fetchServerData(); // renderAll() inside will hide the indicator + update timestamp
        if (btn) { btn.textContent = '↻ Refresh'; btn.disabled = false; }
      } else {
        setTimeout(() => waitForRefreshComplete(startedAt, btn), 4000);
      }
    })
    .catch(() => {
      if (btn) { btn.textContent = '↻ Refresh'; btn.disabled = false; }
    });
}
